@host = https://localhost
@port = 7005
@token = CfDJ8FCRYhvmWphIv6S-CTkGGfKm25EIZnwWEV1MNgarKPyJ6moPFQUXIFkKtmjIooh6ZD6dl99ze7o8FI1vr0ZWTHpptHZU6D_Rpo3DOqIWWVy8ROpmbFSQ_Y3D4NwE17L054OKAte4aOVXpYDnR84RBb02LiI0IiI-zdSYFZ1YCyRto0LrrITGpxY7F437c5v-Ig2m7FpQXJRz2HrF5e3VK6oTPYhOL32pmY8Hkxqgz5vv7W9H-ewhZfsih0040vuFrONDPzQPqTM3b2yCEBg0x8D1wN-CFx7QLfgRWanwdBsWp9IMAl_mFvSBbxsHiYX6rTkRxASHxFU2HdFibgnJQpOeu8oA1S7gKl8mMAahItbgvbe7JQnCKkAuZ1zr0y99HasSC7XICr6zqYLlvfpK6p2KlcsB131v6Eq3QnFtIaSFXU7aEIf6gogvzgxxm5v8vxtSqrWI3dG-vrTbLZcrfVbSLfwn985K04q3O10cwY7bi6sArq8v0waqn3e4uFlftmSanjapRxKmGvq7VT6MEIgx5PmDJvu89K2io4OZVydxlBRc5MpanUa11lD97juX7azEQAyPykTTm7fpAR5Djpw1vQ2CCZh2oamRw2_t1I9qYmugzOctMMS6xKvT3XU14TW6ue6c9r43USDYviYGSlajBsCCtwBvuqwe8okQ3tB52ig5HtfYcQ-PFJT73Izpsi3-ox3CvYtWHwh6rztsAIMMeoEpiBoxYySowae_70h2VfOFHsuSTcPJWA7LcJp4jg

@Restaurants.API_HostAddress = https://localhost:7160


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

@id=2
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1

###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json

{
  "name": "Buraasdadaksss",
      "description": "McDonald's Corporation (McDonald's), incorporated on December 21, 1964, operates and franchises McDonald's restaurants."


}

###
@restaurantId = 2
POST {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "Name": "Deneme",
  "Description": "Description",
  "Price": 18,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes

###

@dishId=0
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

POST  {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@g.com",
  "password": "60403Res..!"
}

###

POST  {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "b@g.com",
  "password": "60403Res..!",
  "twoFactorCode": "string",
  "twoFactorRecoveryCode": "string"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity
Content-Type: application/json

{
  //UpdateUserDetailsCommand
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer CfDJ8FCRYhvmWphIv6S-CTkGGfIppw0WTTPgvwGRPzx6eV3CS0zQuQ3k1z8GoBwcYbf56evGrNhJvwVNNabC2iCmbbuYv8IzTpZi_UIvLmVMlmoE8u3pVN8WdvQL5_rO6uiSpCKpCZmwYQEpP6FcxdI1q63RMLJ30esb6A9AtAJk3njbxEdvoQVqhTdX-CSaFHpji479iBjJvam3_BwqOv29RpP68_Ok5n0esMVcoGRc_C6g38noEty-CL-_2Ac4oEwNOT-yZHPLbsO-mngP7MODbiIhRnHA57GYDBr4Hpa0nWi0fYYyaYLHNuokvoDyS1xGyV70No-0VUEXbI4_0pK-ttiGV5NbGEkkF4rggJLviVBR0XrXvNc45-WKI3gcP28ixJ77pvUf7DlWzGLAc-AGVLpby13igVg4AXq5Skr_LmGxc577b2VCZmvCHa1dCf7c9QE8k7IcwcEbs3qunA7FaoWuklakBYGa1y_ThTkEA3bKI94lOmUhrCr1U_6E_oUIZAaRKwBGvBnqMx6ol-JeGuTsqJdqIjD4HznB9dRrwFH0ExInUi7-vAD0DtSC3lg6LyDg-yVi2I8-A8ER_hjCRx-D9HqQVc48Flvmv-vZdrSDKnHnd9Hch6BpWAyIb0afB_VG8N4gg7T5rz0Wd9PxNDQ8eWlyxy9mQC5JtveJyLuLef6MWhkPPBaKJtIZ4VxBMxmtxMfWBctU3uS8GQGjUWf5KZK8eU-4-m-aBgNkhc7wQNSZ6_SKyMdiBeneQCTB0_0MeIlONE4Ezd7CKQDfomA
{
  
  "userEmail": "b@g.com",
  "roleName": "User"
  
}