@host = https://localhost
@port = 7005
@token = CfDJ8FCRYhvmWphIv6S-CTkGGfKrp1m54YIrIS9ctyStL8Wus2tCqP44uvhCa4UCcoeRJMnN8pMO2WEuh2TGvHjaOG6Gwfzfv_PbQ309hHLlshuTFs6omsOhk32g4Ld5zcVOz9K5CcgtXvRjIh0WZXYV4uUvfpHSidn9Wkl3cowpOIkWJ0zvOAuGmjyUUtCS63S9QdYKVcx7z_lZ_HS00yFOgW-WkKFwhAAL0eO3fZYYXnRJlvGvpZg8Ab_bDq8mDyMbm4DqM7t-n3Cs2qd1lpTdHWkW3fze-pOfftBcbKODz6WKCIyqPSxiVXgYa6XnljusBsp3eDlJ0xQNufCLyACDLrdBlGlcRURtA99Qo7xomSjabzDZOwjKhp6b9IqGPHlMkuNlzpJyCdMxYrkmBYikCP9cdtgWB_9NGCFZcPWc75j1Xzh-HgBbvFXXBpeMlhTodFbv0gIq4bX9vnOKQ3rFwGXHsD8J0TpjjQatL7UX8nH4OtYX1U-2mYyU8o5YQ29tn4QOKcqdW5FDmW-rnLzNkVr25ky4kzCR32XoLd4uJgdUWXcb4uZ5i3AvYTJvAqK4RVyb-kcqPOJ0-WhTgAdZJiMg0uuk_zOq3_k4Ip-7lFLamGIMC5Fr6HpCp0OePaz2ks5OcCeScpIZ7otj0y356hh-WSiq6p2TrtMtCedvpD2gT-KzigR0jlomtn6U_EjVsHPflXfRI-li_m_r1NouCOnC-25MXyJzO_cTtgI0Dv3C8Gm532dMqYREvwgY2B4hqt5_nN6ects3m_b7cvhOqAA

@Restaurants.API_HostAddress = https://localhost:7160


GET {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
###

@id=4
GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Authorization: Bearer {{token}}
###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  
}

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1

###



PATCH {{Restaurants.API_HostAddress}}/api/restaurants/2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Buraasdadaksss",
      "description": "McDonald's Corporation (McDonald's), incorporated on December 21, 1964, operates and franchises McDonald's restaurants."

}

###
@restaurantId = 2
POST {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes
Content-Type: application/json

{
  "Name": "Deneme",
  "Description": "Description",
  "Price": 18,
  "KiloCalories": 750
}

###

GET {{Restaurants.API_HostAddress}}/api/restaurant/1/dishes

###

@dishId=0
GET {{Restaurants.API_HostAddress}}/api/restaurant/2/dishes/3

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurant/{{restaurantId}}/dishes

###

POST  {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "user@g.com",
  "password": "60403Res..!"
}

###

POST  {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "owner@g.com",
  "password": "60403Res..!",
  "twoFactorCode": "string",
  "twoFactorRecoveryCode": "string"
}

###

PATCH {{Restaurants.API_HostAddress}}/api/identity
Content-Type: application/json

{
  //UpdateUserDetailsCommand
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/userRole
Content-Type: application/json
Authorization: Bearer CfDJ8FCRYhvmWphIv6S-CTkGGfIppw0WTTPgvwGRPzx6eV3CS0zQuQ3k1z8GoBwcYbf56evGrNhJvwVNNabC2iCmbbuYv8IzTpZi_UIvLmVMlmoE8u3pVN8WdvQL5_rO6uiSpCKpCZmwYQEpP6FcxdI1q63RMLJ30esb6A9AtAJk3njbxEdvoQVqhTdX-CSaFHpji479iBjJvam3_BwqOv29RpP68_Ok5n0esMVcoGRc_C6g38noEty-CL-_2Ac4oEwNOT-yZHPLbsO-mngP7MODbiIhRnHA57GYDBr4Hpa0nWi0fYYyaYLHNuokvoDyS1xGyV70No-0VUEXbI4_0pK-ttiGV5NbGEkkF4rggJLviVBR0XrXvNc45-WKI3gcP28ixJ77pvUf7DlWzGLAc-AGVLpby13igVg4AXq5Skr_LmGxc577b2VCZmvCHa1dCf7c9QE8k7IcwcEbs3qunA7FaoWuklakBYGa1y_ThTkEA3bKI94lOmUhrCr1U_6E_oUIZAaRKwBGvBnqMx6ol-JeGuTsqJdqIjD4HznB9dRrwFH0ExInUi7-vAD0DtSC3lg6LyDg-yVi2I8-A8ER_hjCRx-D9HqQVc48Flvmv-vZdrSDKnHnd9Hch6BpWAyIb0afB_VG8N4gg7T5rz0Wd9PxNDQ8eWlyxy9mQC5JtveJyLuLef6MWhkPPBaKJtIZ4VxBMxmtxMfWBctU3uS8GQGjUWf5KZK8eU-4-m-aBgNkhc7wQNSZ6_SKyMdiBeneQCTB0_0MeIlONE4Ezd7CKQDfomA
{
  
  "userEmail": "b@g.com",
  "roleName": "User"
  
}